<a href="https://colab.research.google.com/github/JyothiAB/NLP/blob/main/SPAM_Classifier_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df1 = pd.read_csv('https://raw.githubusercontent.com/JyothiAB/NLP/main/train1.csv')

In [ ]:
df2 = pd.read_csv('https://raw.githubusercontent.com/JyothiAB/NLP/main/train2.csv')
df3 = pd.read_csv('https://raw.githubusercontent.com/JyothiAB/NLP/main/train3.csv')
df4 = pd.read_csv('https://raw.githubusercontent.com/JyothiAB/NLP/main/train4.csv')
df5 = pd.read_csv('https://raw.githubusercontent.com/JyothiAB/NLP/main/train5.csv')

In [ ]:
df = pd.concat([df1,df2,df3,df4,df5], axis=0)

In [ ]:
df

Unnamed: 0     id                                              title  \
0             0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1             1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2             2      2                  Why the Truth Might Get You Fired   
3             3      3  15 Civilians Killed In Single US Airstrike Hav...   
4             4      4  Iranian woman jailed for fictional unpublished...   
..          ...    ...                                                ...   
794       20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
795       20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
796       20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
797       20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
798       20799  20799                          What Keeps the F-35 Alive   

                                        author  \
0                                Darrell Lucus   
1                              Daniel J. Flynn   
2                           Consortiumnews.com   
3                              Jessica Purkiss   
4                               Howard Portnoy   
..                                         ...   
794                              Jerome Hudson   
795                           Benjamin Hoffman   
796  Michael J. de la Merced and Rachel Abrams   
797                                Alex Ansary   
798                              David Swanson   

                                                  text  label  
0    House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1    Ever get the feeling your life circles the rou...      0  
2    Why the Truth Might Get You Fired October 29, ...      1  
3    Videos 15 Civilians Killed In Single US Airstr...      1  
4    Print \nAn Iranian woman has been sentenced to...      1  
..                                                 ...    ...  
794  Rapper T. I. unloaded on black celebrities who...      0  
795  When the Green Bay Packers lost to the Washing...      0  
796  The Macy’s of today grew from the union of sev...      0  
797  NATO, Russia To Hold Parallel Exercises In Bal...      1  
798    David Swanson is an author, activist, journa...      1  

[20800 rows x 6 columns]

In [ ]:
X = df[['title','text']]
y = df['label']

In [ ]:
X.shape

(20800, 2)

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding

In [ ]:
#Data preprocessing
message = X.copy()

In [ ]:
message.reset_index(inplace=True)

In [ ]:
message

index                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795    794  Rapper T.I.: Trump a ’Poster Child For White S...   
20796    795  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797    796  Macy’s Is Said to Receive Takeover Approach by...   
20798    797  NATO, Russia To Hold Parallel Exercises In Bal...   
20799    798                          What Keeps the F-35 Alive   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[20800 rows x 3 columns]

In [ ]:
import nltk
import re

from nltk.corpus import stopwords
from nltk import WordNetLemmatizer
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
lm = WordNetLemmatizer()
title = []
for i in range(0,len(message)):
  review_title = re.sub('[^a-zA-Z]', ' ', str(message['title'][i]))
  review_title = review_title.lower()
  review_title = review_title.split()

  review_title = [lm.lemmatize(words) for words in review_title if not words in stopwords.words('english')]
  review_title = ' '.join(review_title)

  title.append(review_title)
print(title)                  

['house dem aide even see comey letter jason chaffetz tweeted', 'flynn hillary clinton big woman campus breitbart', 'truth might get fired', 'civilian killed single u airstrike identified', 'iranian woman jailed fictional unpublished story woman stoned death adultery', 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart', 'life life luxury elton john favorite shark picture stare long transcontinental flight', 'beno hamon win french socialist party presidential nomination new york time', 'excerpt draft script donald trump q ampa black church pastor new york time', 'back channel plan ukraine russia courtesy trump associate new york time', 'obama organizing action partner soros linked indivisible disrupt trump agenda', 'bbc comedy sketch real housewife isi cause outrage', 'russian researcher discover secret nazi military base treasure hunter arctic photo', 'u official see link trump russia', 'yes paid government troll social medium blo

In [ ]:
#One hot representation
title_one_hot = [one_hot(words,5000) for words in title]
print(title_one_hot)


[[4628, 4135, 4385, 770, 2298, 881, 241, 4480, 3171, 1483], [4657, 4773, 3138, 11, 3580, 1137, 3602], [4261, 2864, 4955, 1485], [522, 2204, 2802, 130, 222, 2647], [3376, 3580, 3060, 715, 1565, 4777, 3580, 3769, 1982, 2071], [1833, 4011, 4144, 3789, 1632, 1572, 644, 4968, 4001, 4960, 642, 959, 760, 2084, 3602], [2754, 2754, 4822, 1568, 2062, 1242, 3738, 2310, 3432, 279, 2834, 2387], [2746, 4017, 3972, 4716, 4348, 4838, 4935, 2843, 426, 504, 4697], [4580, 692, 4383, 2366, 1572, 4885, 1828, 703, 755, 3630, 426, 504, 4697], [1289, 2334, 2235, 2483, 2647, 1288, 1572, 3441, 426, 504, 4697], [4579, 2187, 1082, 901, 3524, 483, 3900, 1995, 1572, 28], [2185, 2008, 788, 2181, 3690, 2275, 1656, 1117], [4163, 354, 1529, 982, 2729, 3101, 1264, 1407, 1050, 714, 2187], [130, 35, 2298, 515, 1572, 2647], [3708, 1810, 2487, 4557, 2849, 984, 3240, 4834, 957], [733, 4061, 2389, 2414, 709, 352, 292, 426, 504, 4697], [2190, 4660, 382, 2588, 4681, 426, 504, 4697], [721, 3096, 924, 4687, 1478, 545, 3330, 4878,

In [ ]:
#Padding
title_pad = pad_sequences(title_one_hot,maxlen=20, padding='pre')
print(title_pad)

[[   0    0    0 ... 4480 3171 1483]
 [   0    0    0 ... 3580 1137 3602]
 [   0    0    0 ... 2864 4955 1485]
 ...
 [   0    0    0 ...  426  504 4697]
 [   0    0    0 ... 4841 2932 2203]
 [   0    0    0 ... 1606 4035  225]]


In [ ]:
#Training and Testing Data from actual data
from sklearn.model_selection import train_test_split
x_training,x_test,y_training,y_test = train_test_split(title_pad,y,test_size=0.1,random_state=20)

In [ ]:
#Training and Validation Data from Training data
x_train, x_val, y_train, y_val = train_test_split(x_training,y_training,test_size=0.1,random_state=30)

In [ ]:
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras import optimizers

def model_builder(hp):
  model = Sequential()
  model.add(Embedding(input_dim=5000, output_dim=40, input_length=20))
  model.add(LSTM(units=hp.Int('units_', min_value=32, max_value=512, step=32), activation='relu'))
  model.add(Dense(1,activation='sigmoid'))

  # Tune the learning rate for the optimizer
  # Choose an optimal value from 0.01, 0.001, or 0.0001
  hp_learning_rate = hp.Choice('learning_rate', values=[0.01, 0.001, 0.0001])
  model.compile(optimizer= optimizers.Adam(learning_rate=hp_learning_rate),
                loss='binary_crossentropy',
                metrics=['accuracy'])

  return model

In [ ]:
!pip install -q -U keras-tuner
import kerastuner as kt

from kerastuner.tuners import RandomSearch
tuner = RandomSearch(model_builder,
                     objective='val_accuracy',
                     max_trials=5,
                     executions_per_trial =3)



In [ ]:
tuner.search_space_summary()

Search space summary
Default search space size: 2
units_ (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
learning_rate (Choice)
{'default': 0.01, 'conditions': [], 'values': [0.01, 0.001, 0.0001], 'ordered': True}


In [ ]:
tuner.search(x_train,y_train,epochs=50, validation_data=[x_test,y_test])

Trial 1 Complete [01h 33m 59s]
val_accuracy: 0.932852546374003

Best val_accuracy So Far: 0.932852546374003
Total elapsed time: 01h 34m 13s

Search: Running Trial #2

Value             |Best Value So Far |Hyperparameter
192               |352               |units_
0.0001            |0.001             |learning_rate

Epoch 1/50
527/527 [==============================] - 36s 65ms/step - loss: 0.4479 - accuracy: 0.7935 - val_loss: 0.2436 - val_accuracy: 0.9130
Epoch 2/50
527/527 [==============================] - 34s 65ms/step - loss: 0.2150 - accuracy: 0.9148 - val_loss: 0.2152 - val_accuracy: 0.9187
Epoch 3/50
527/527 [==============================] - 34s 65ms/step - loss: 0.1689 - accuracy: 0.9326 - val_loss: 0.2089 - val_accuracy: 0.9163
Epoch 4/50
527/527 [==============================] - 34s 65ms/step - loss: 0.1380 - accuracy: 0.9450 - val_loss: 0.1781 - val_accuracy: 0.9284
Epoch 5/50
527/527 [==============================] - 34s 65ms/step - loss: 0.1144 - accuracy: 0.9566 - va

In [ ]:
hp = kt.HyperParameters()
for i in range(hp.Int('num_layers', 2, 20)):
  hp_units = hp.Int('units',32,512,32)
  print(hp_units)

In [ ]:
def model_builder(hp):
  model = keras.Sequential()
  model.add(Embedding(5000,40,20)

  hp = keras_tuner.HyperParameters()
      
  # Tune the number of units in the first Dense layer
  # Choose an optimal value between 32-512
  hp_units = hp.Int('units' + min_value, min_value=32, max_value=512, step=32)
  keys = ['layers','activation_func','learning_rate']
  model.add(LSTM(units=hp_units, activation='relu'))
  model.add(Dense(1, activation='relu'))

  # Tune the learning rate for the optimizer
  # Choose an optimal value from 0.01, 0.001, or 0.0001
  hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])

  model.compile(optimizer=keras.optimizers.Adam(learning_rate=hp_learning_rate),
                loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy'])

  return model

In [ ]:
hp = keras_tuner.HyperParameters()
hp_units = hp.Int('units' + min_value, min_value=32, max_value=512, step=32)